apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flaskapp.fullname" . }}-flaskapi-secrets
  labels:
  {{- include "flaskapp.labels" . | nindent 4 }}
data:
  db_root_password: {{ .Values.flaskapiSecrets.dbRootPassword
    | b64enc | quote }}
type: Opaque
