apiVersion: v1
kind: Service
metadata:
  name: {{ include "flaskapp.fullname" . }}-flask-service
  labels:
  {{- include "flaskapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.flaskService.type }}
  selector:
    app: flaskapi
  {{- include "flaskapp.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.flaskService.ports | toYaml | nindent 2 -}}