apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
  {{- include "flaskapp.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.mysqlPvClaim.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.mysqlPvClaim.storageClass | quote }}
